In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import metrics
import pickle

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
df = pd.read_csv("/content/drive/MyDrive/DatasetMedication.csv")
df.head()

Gender  Age Pain Intensity Swelling Diab Hypertensive Cardiac  \
0    male   40        severe         Y    N            Y       Y   
1  female   35          mild         N    N            Y       N   
2    male   42         normal        N    Y            Y       N   
3    male   15         normal        N    N            N       N   
4  female   34         normal        N    N            N       N   

  Liver Transplant Kidney Transplant  Drugs  
0                N                 N  DrugB  
1                N                 N  DrugA  
2                N                 N  DrugA  
3                N                 N  DrugC  
4                N                 N  DrugC

In [4]:
# Convert values to lowercase for specific columns
lowercase_columns = ['Swelling', 'Diab', 'Hypertensive', 'Cardiac', 'Liver Transplant', 'Kidney Transplant']
for col in lowercase_columns:
    df[col] = df[col].str.lower()

In [5]:
# Apply label encoding
for col in ['Gender', 'Pain Intensity', 'Swelling', 'Diab', 'Hypertensive', 'Cardiac', 'Liver Transplant', 'Kidney Transplant']:
    converter = LabelEncoder()
    df[col] = converter.fit_transform(df[col])

In [6]:
X = df[['Gender', 'Age', 'Pain Intensity', 'Swelling', 'Diab', 'Hypertensive', 'Cardiac', 'Liver Transplant', 'Kidney Transplant']].values
y = df['Drugs'].values
print("Independent variable matrix:\n{}\n\n Dependent variable matrix:\n{}".format(X[:3], y[:3]))

Independent variable matrix:
[[ 1 40  3  1  0  1  1  0  1]
 [ 0 35  1  0  0  1  0  0  1]
 [ 1 42  2  0  1  1  0  0  1]]

 Dependent variable matrix:
['DrugB' 'DrugA' 'DrugA']


In [7]:
# Split the data into training and test sets
training_X, test_X, training_y, test_y = train_test_split(X, y, test_size=0.25)


In [8]:
# Create an SVM classifier with linear kernel
svm_model = svm.SVC(kernel='linear')

In [9]:
# Fit the training data to the SVM model
svm_model.fit(training_X, training_y)

SVC(kernel='linear')

In [10]:
# Make predictions using the SVM model
svm_predictions = svm_model.predict(test_X)

In [11]:
# Evaluate the performance of the SVM model
accuracy = metrics.accuracy_score(test_y, svm_predictions)
print("Accuracy of our SVM model: %.2f" % accuracy)

Accuracy of our SVM model: 0.90


In [12]:
# Save the trained SVM model to a file
with open('svm_model.pkl', 'wb') as file:
    pickle.dump(svm_model, file)